version: "3.9"

networks:
  app-network:

volumes:
  api-logs:

services:
  reverseproxy:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - 80:80
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  todoapi:
    build: ./api
    image: alcompilor/todoapi:1.0
    container_name: todo_api
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - reverseproxy
    volumes:
      - api-logs:/app/logs
  
  todoclient:
    build: ./client
    image: alcompilor/todoclient:1.0
    container_name: todo_client
    ports:
      - 5000:5000
    networks:
      - app-network
    environment:
      - API_ENDPOINT="/api"
    depends_on:
      - todoapi